package se.lexicon.model;

import java.util.Objects;

public class Customer {
    // Fields
    private Integer id;
    private String name;
    private String phoneNumber;
    private String vehiclePlateNumber;

    public Customer(Integer id, String name, String phoneNumber, String vehiclePlateNumber) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.vehiclePlateNumber = vehiclePlateNumber;
    }

    public Integer getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public String getVehiclePlateNumber() {
        return vehiclePlateNumber;
    }

    public void setId(Integer id) {
        Objects.requireNonNull(id, "Id cannot be null");
        this.id = id;
    }

    public void setName(String name) {
        // todo: add validation
        this.name = name;
    }

    public void setPhoneNumber(String phoneNumber) {
        // todo: add validation - recommendation is to use PATTERN or regex
        this.phoneNumber = phoneNumber;
    }

    public void setVehiclePlateNumber(String vehiclePlateNumber) {
        // todo: add validation - recommendation is to use PATTERN or regex
        this.vehiclePlateNumber = vehiclePlateNumber;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", vehiclePlateNumber='" + vehiclePlateNumber + '\'' +
                '}';
    }
}
/* Interger Vs int Explanation
In the Customer class (and other classes like ParkingSpot), Integer is used instead of the primitive int for several
key reasons related to object-oriented design and Java's features:
1. Handling "Null" Values
The most significant difference is that an Integer can be null, whereas an int cannot (it defaults to 0).
•
Database Integration: In many applications, an Id is generated by a database. Before a Customer is saved to the database,
 it might not have an Id yet. Using Integer allows the id field to be null to represent a "not yet persisted" state.
•
Validation: In your setId method, there is a check: Objects.requireNonNull(id, "Id cannot be null");. This validation is
only possible because Integer is an object.
2. Compatibility with Generics and Collections
Java Generics (like List, Map, or Optional) do not support primitive types.
•
If you look at your CustomerDao interface, you have: Optional<Customer> findById(Integer id);.
•
If you wanted to store IDs in a List<Integer>, you must use the wrapper class.
3. Consistency in the DAO Pattern
In the CustomerDao.java file, the methods use Integer:
Optional<Customer> findById(Integer id);
void remove(Integer id);
By using Integer in the model class (Customer), the code remains consistent with the Data Access Object (DAO) layer,
which often relies on object-based identifiers for searching and deleting records.
Summary
While int is slightly more memory-efficient, Integer provides the flexibility of nullability and compatibility with Java
 Collections and Generics, which are essential for building robust data-driven applications.
""*/